apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007 # You can specify a port in the range 30000-32767 or let Kubernetes choose one
  type: NodePort
